# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0011_auto_20171118_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL/Link')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is landing active?')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='Date changed')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Landing',
                'verbose_name_plural': 'Landings',
                'ordering': ['-date_added'],
            },
        ),
    ]
