# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 22:43
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0012_auto_20171125_1631'),
        ('landing', '0002_auto_20171125_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('template_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/landing', location='/home/dmitry/Projects/Python/django/filingroup/landing/templates/'), upload_to='', verbose_name='Template file (HTML file)')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is landing active?')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='Date changed')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course', to_field='slug', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Landing',
                'verbose_name_plural': 'Landings',
                'ordering': ['-date_added'],
            },
        ),
    ]
