# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20171129_0005'),
        ('landing', '0006_auto_20171126_2131'),
    ]

    operations = [
    ]
