# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 17:02
from __future__ import unicode_literals

import about_us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Type of content (first try, etc.)')),
                ('logo', models.FileField(upload_to=about_us.models.upload_path, verbose_name='About Us')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is About description active?')),
                ('text', models.TextField(verbose_name='Text')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name_plural': 'About Us',
                'verbose_name': 'About Us',
            },
        ),
    ]
