# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.IntegerField(default=0, verbose_name='score'),
        ),
    ]
