# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Version of site rules')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is this version active?')),
                ('content', models.TextField(verbose_name='Content')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name': 'Site Rule',
                'ordering': ['-date_added'],
                'verbose_name_plural': 'Site Rules',
            },
        ),
    ]
