# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 21:31
from __future__ import unicode_literals

import courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('slug', models.SlugField()),
                ('places', models.IntegerField(verbose_name='Places to course')),
                ('description', models.TextField(verbose_name='About the course')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('is_active', models.BooleanField(verbose_name='Is course active?')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
            ],
            options={
                'ordering': ['-date_added'],
                'verbose_name_plural': 'Courses',
                'verbose_name': 'Course',
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last name')),
                ('avatar', models.FileField(blank=True, null=True, upload_to=courses.models.upload_path, verbose_name='Avatar')),
                ('link_to_fb', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link to Facebook')),
                ('link_to_inst', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link to Instagram')),
                ('link_to_linkedin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link to LinkedIn')),
                ('review', models.TextField(verbose_name='Review')),
                ('video', models.FileField(blank=True, null=True, upload_to=courses.models.upload_path, verbose_name='Video review')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'ordering': ['-date_added'],
                'verbose_name_plural': 'Courses reviews',
                'verbose_name': 'Course review',
            },
        ),
        migrations.CreateModel(
            name='CourseTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('F_S', 'Fast start'), ('A_I', 'All-inclusive'), ('P', 'Premium')], default='F_S', max_length=50, verbose_name='Permission')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('is_active', models.BooleanField(verbose_name='Is course type active?')),
                ('description', models.TextField(verbose_name='Description')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name_plural': 'Course types',
                'verbose_name': 'Course type',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField()),
                ('percents', models.IntegerField(verbose_name='Percents')),
                ('from_date', models.DateField(verbose_name='From')),
                ('till_date', models.DateField(verbose_name='Till')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name_plural': 'Discounts',
                'verbose_name': 'Discount',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone')),
                ('skype', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Skype')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('courses', models.ManyToManyField(to='courses.Course', verbose_name='Courses')),
            ],
            options={
                'ordering': ['-date_added'],
                'verbose_name_plural': 'Students',
                'verbose_name': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('avatar', models.FileField(blank=True, null=True, upload_to=courses.models.upload_path, verbose_name='Avatar')),
                ('age', models.DateField(verbose_name='Age')),
                ('description', models.TextField(blank=True, null=True, verbose_name='About teacher')),
            ],
            options={
                'verbose_name_plural': 'Teachers',
                'verbose_name': 'Teacher',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Discount', verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(to='courses.Teacher', verbose_name='Teachers'),
        ),
    ]
