# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='free_places',
            field=models.IntegerField(blank=True, null=True, verbose_name='Free places'),
        ),
    ]
