# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_free_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F_S', 'Fast start'), ('A_I', 'All-inclusive'), ('P', 'Premium')], default='F_S', max_length=50, verbose_name='Type')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
            ],
            options={
                'verbose_name': 'Privilege',
                'verbose_name_plural': 'Privileges',
            },
        ),
        migrations.RemoveField(
            model_name='coursetypes',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursetypes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coursetypes',
            name='permission',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.CourseTypes', verbose_name='Course type'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='courses',
            field=models.ManyToManyField(to='courses.Course', verbose_name='Courses'),
        ),
    ]
