# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20171115_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='Name', max_length=50, verbose_name='Name'),
        ),
    ]
