# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 13:02
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20171116_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_picture',
            field=models.FileField(blank=True, upload_to=courses.models.upload_path, verbose_name='Course picture'),
        ),
    ]
