# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_course_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title'),
        ),
    ]
