# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20171117_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='consulting_time',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Consulting time'),
        ),
        migrations.AddField(
            model_name='course',
            name='consulting_time_availability_on_this_week',
            field=models.BooleanField(choices=[(True, 'AVAILABLE'), (False, 'BUSY')], default=False, verbose_name='Consulting time availability on this week'),
        ),
        migrations.AddField(
            model_name='course',
            name='couching_consult_time',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Couching consult time'),
        ),
        migrations.AddField(
            model_name='course',
            name='couching_time_availability_on_this_month',
            field=models.BooleanField(choices=[(True, 'AVAILABLE'), (False, 'BUSY')], default=False, verbose_name='Couching time availability on this month'),
        ),
        migrations.AddField(
            model_name='course',
            name='couching_timing',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Couching timing'),
        ),
    ]
