# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20171117_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='link_to_vk',
            field=models.URLField(blank=True, null=True, verbose_name='Link to Vkontakte'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='link_to_fb',
            field=models.URLField(blank=True, null=True, verbose_name='Link to Facebook'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='link_to_inst',
            field=models.URLField(blank=True, null=True, verbose_name='Link to Instagram'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='link_to_linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Link to LinkedIn'),
        ),
    ]
