# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20171125_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='Avatar (link to google drive, etc.)'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Video review (link to google drive, etc.)'),
        ),
    ]
