# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20171130_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='avatar',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Avatar (link to google drive, etc.)'),
        ),
    ]
