# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending_agreement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is agreement active?'),
        ),
    ]
