# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_auto_20171106_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('billing_last_name', models.CharField(max_length=60, verbose_name='Last name')),
                ('billing_phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('billing_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('order_sum', models.IntegerField(verbose_name='Sum')),
                ('pay_status', models.BooleanField(verbose_name='Pay status')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Course', verbose_name='Course')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Discount', verbose_name='Discount')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-date_added'],
            },
        ),
    ]
